-- SQL initialization is intentionally disabled in application properties.
-- Demo data is created by the dev-only CommandLineRunner when app.seed.enabled=true.
-- Keep this file free of MySQL-specific statements so enabling SQL init cannot break PostgreSQL startup.
